import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import  ThemeProvider  from "../providers/ThemeProvider";
import { AuthProvider } from "@/providers/AuthProvider";

import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`} >
        <ThemeProvider >
          <AuthProvider>
            <ReactQueryProvider>
            <Toaster position="top-center" reverseOrder={false} />
           {children}
           </ReactQueryProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
